### ISSUE TITLE
The composer.json does not allow using Safe in version > 2 which is the actual one

### ISSUE THREAD

**Issue by smit-daniel** [DobryProgramator/DoctrineSafeTypes#2]

**Comment by smit-daniel** [comment]
https://github.com/smit-daniel/DoctrineSafeTypes

**Comment by Holicz** [comment]
Fixed, but thecodingmachine/safe does not have any changelog though, so I can't really check what changed and I am not using this library anymore. So in any case of any bug please create a new issue (and ideally a MR :) ).

Thanks for submitting this!
